// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTuDXsUI4By1uiUE1cLUFSJ_wPJj7h2lM',
    appId: '1:942021581318:web:13a8dd85a3f021ff098187',
    messagingSenderId: '942021581318',
    projectId: 'easy-learn-chat',
    authDomain: 'easy-learn-chat.firebaseapp.com',
    storageBucket: 'easy-learn-chat.firebasestorage.app',
    measurementId: 'G-GBWXYDSDCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6lFPKotQqexvK_8P8_pju-KywcfF2UY',
    appId: '1:942021581318:android:d0d4ae4305149475098187',
    messagingSenderId: '942021581318',
    projectId: 'easy-learn-chat',
    storageBucket: 'easy-learn-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEJhK2USN8miyaMgwetD3mFcJ4sSUiono',
    appId: '1:942021581318:ios:628c1f2ec74c5a30098187',
    messagingSenderId: '942021581318',
    projectId: 'easy-learn-chat',
    storageBucket: 'easy-learn-chat.firebasestorage.app',
    iosBundleId: 'com.example.easyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEJhK2USN8miyaMgwetD3mFcJ4sSUiono',
    appId: '1:942021581318:ios:628c1f2ec74c5a30098187',
    messagingSenderId: '942021581318',
    projectId: 'easy-learn-chat',
    storageBucket: 'easy-learn-chat.firebasestorage.app',
    iosBundleId: 'com.example.easyChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTuDXsUI4By1uiUE1cLUFSJ_wPJj7h2lM',
    appId: '1:942021581318:web:d90a7f755fa68d24098187',
    messagingSenderId: '942021581318',
    projectId: 'easy-learn-chat',
    authDomain: 'easy-learn-chat.firebaseapp.com',
    storageBucket: 'easy-learn-chat.firebasestorage.app',
    measurementId: 'G-DE9C9CP6K9',
  );
}
